# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

Meta-Llama-3-70B-Instruct-GPTQ:
     model_name: /home/jupyter/models/Meta-Llama-3-70B-Instruct-GPTQ
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

Phi-3-medium-128k-instruct:
     model_name: /home/jupyter/models/Phi-3-medium-128k-instruct
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16
  
atech-splitnews-vikhr04-0105-unsloth:
     model_name: /home/jupyter/models/atech-splitnews-vikhr04-0105-unsloth
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

Meta-Llama-3-8B-Instruct-f16:
     model_name: /home/jupyter/models/Meta-Llama-3-8B-Instruct-f16
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

aya-23-8B:
     model_name: /home/jupyter/models/aya-23-8B
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

Vikhr-7B-instruct_0.5:
     model_name: /home/jupyter/models/Vikhr-7B-instruct_0.5
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

suzume-llama-3-8B-multilingual:
     model_name: /home/jupyter/models/suzume-llama-3-8B-multilingual
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

Llama-3-70B-Instruct-AH-AWQ:
     model_name: /home/jupyter/models/Llama-3-70B-Instruct-AH-AWQ
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

alpindale_gemma-2b-it:
     model_name: /home/jupyter/models/alpindale_gemma-2b-it
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

suzume-llama-3-8B-multilingual-orpo-borda-half:
     model_name: /home/jupyter/models/suzume-llama-3-8B-multilingual-orpo-borda-half
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

SELM-Llama-3-8B-Instruct-iter-3:
     model_name: /home/jupyter/models/SELM-Llama-3-8B-Instruct-iter-3
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16

Llama-3-Instruct-8B-SimPO:
     model_name: /home/jupyter/models/Llama-3-Instruct-8B-SimPO
     endpoints:
         - api_base: http://localhost:8010/v1
           api_key: token-abc123
     api_type: openai
     parallel: 16