name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 1520
num_choices: 1

# a list of model to generate answers
model_list:
  - Llama-3-Instruct-8B-SimPO
